name: Generate snake game

on:
  schedule: #execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
          github_user_name: DanielBBrasileiro
          svg_out_path: dist/github-snake.svg
          snake_color: 'blue'
